# pylint: disable=C0114,C0116,C0103

import datetime
from datetime import datetime
import json
import os
from pathlib import Path
import pandas as pd
import psycopg2

os.chdir(Path(__file__).parent.parent.resolve())

csvFile = "SELLOUT_SELLIN_ESTOQUE_HISTORICO_26246169000110_20250606_032528_v02.csv"

df = pd.read_csv(f"datasets/{csvFile}", sep=",", encoding="utf-8", dtype=str)

PG_HOST = "54.174.91.231"  # Change to your PostgreSQL host if needed
OLLAMA_HOST = "http://54.174.91.231"

def connect_db():
    connection = psycopg2.connect(
        host=PG_HOST,
        database="postgres",
        user="postgres",
        password="postgres",
        port="5432",
    )
    connection.autocommit = True
    return connection


def create_db():
    with connect_db() as conndb:
        with conndb.cursor() as curdb:
            curdb.execute(
                """
                CREATE TABLE IF NOT EXISTS document_embedding (
                    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
                    metadata JSONB,
                    content TEXT,
                    embedding VECTOR(4096)
                );
            """
            )


if __name__ == "__main__":

    with connect_db() as conn:
        with conn.cursor() as cur:
            for doc in df.to_dict(orient="records"):
                doc.setdefault(
                    "METADATA",
                    json.dumps(
                        {
                            "file": csvFile,
                            "timestamp": datetime.now().isoformat(),
                            "tags": ["python", "postgresql", "jsonb"],
                            "version": 1.0,
                        }
                    ),
                )

                cur.execute(
                    """
                    INSERT INTO document_embedding (metadata, content, embedding)
                    VALUES (
                        %(METADATA)s,
                        %(RESPONSE)s,
                        ai.ollama_embed(
                            'bert_tiny_embeddings_english_portuguese-unsloth',
                            concat(%(INSTRUCTION)s, ' - ', %(RESPONSE)s),
                            host=>'http://54.174.91.231:11434'
                        )
                    );
                    """,
                    doc,
                )

    with connect_db() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """
                SELECT metadata, content, embedding
                FROM document_embedding;
            """
            )

            rows = cur.fetchall()
            for row in rows:
                print(
                    f"Metadata: {row[0]}\nContent: {row[1]}\nEmbedding: {row[2][0:150]}...\n\n"
                )

    query = "Diga-me sobre a Drogaria Campeã, onde fica, o que vende e o telefone."

    with connect_db() as conn:
        with conn.cursor() as cur:
            # Embed the query using the ollama_embed function
            cur.execute(
                """
                SELECT ai.ollama_embed(
                        'bert_tiny_embeddings_english_portuguese-unsloth',
                        %s,
                        host=>'http://54.174.91.231:11434'
                );
                """,
                (query,),
            )
            query_embedding = cur.fetchone()[0]

            # Retrieve relevant documents based on cosine distance
            cur.execute(
                """
                SELECT metadata, content, 1 - (embedding <=> %s) AS similarity
                FROM document_embedding
                ORDER BY similarity DESC
                LIMIT 3;
                """,
                (query_embedding,),
            )

            rows = cur.fetchall()

            # Prepare the context for generating the response
            context = "\n\n".join(
                [f"Drogaria: {row[0]}\nInformação: {row[1]}" for row in rows]
            )

            # Generate the response using the ollama_generate function
            cur.execute(
                """
                SELECT ai.ollama_generate(
                        'mistral_7b_portuguese-unsloth', %s,
                        host=>'http://54.174.91.231:11434'
                );
                """,
                (f"Query: {query}\nContext: {context}",),
            )

            model_response = cur.fetchone()[0]
            print(model_response["response"])
