-- psql -d "postgres://postgres:postgres@localhost:5432/postgres"
-- \dx
-- \q

SET ROLE postgres;

CREATE EXTENSION vector;

CREATE EXTENSION IF NOT EXISTS vectorscale CASCADE;
CREATE EXTENSION IF NOT EXISTS ai CASCADE;

DROP TABLE IF EXISTS document_embedding;

CREATE TABLE IF NOT EXISTS document_embedding  (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    metadata JSONB,
    content TEXT,
    embedding VECTOR(4096)
)

CREATE INDEX document_embedding_idx ON document_embedding USING diskann (embedding vector_cosine_ops);

SELECT COUNT(*) FROM document_embedding;

WITH query_embedding AS
(
    SELECT ai.ollama_embed(
        'bert_tiny_embeddings_english_portuguese-unsloth',
        'Qual o CNPJ da Drogaria Campeã da Lapa?',
        host => 'http://54.174.91.231:11434') AS embedding
)
SELECT
    t.id,
    t.metadata,
    t.contents,
    t.embedding <=> (SELECT embedding FROM query_embedding) AS distance
FROM document_embedding t
ORDER BY distance ASC
LIMIT 50;

